spring.application.name=yby-api

# Database Supabase PostgreSQL (Usando Session Pooler)
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.sshygmhxrzgnaiakqtki
spring.datasource.password=Ybydb2026!0
spring.datasource.driver-class-name=org.postgresql.Driver

# Pool connection do Hikari local
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000

# Configurações do JPA / Hibernate (Sem busca de metadados e Dialeto Fixo)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Migrations com Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# Documentation API Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs