-- V1 - Schema inicial do JREDD+ Intelligence.
-- Consistente com as entidades JPA (Hibernate roda com ddl-auto=validate sobre este schema).
-- SQL portavel entre PostgreSQL (Supabase) e H2 em modo PostgreSQL (dev/test).

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    email VARCHAR(180) NOT NULL UNIQUE,
    senha_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('GESTOR', 'SERVIDOR')),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    primeiro_acesso_troca_senha BOOLEAN NOT NULL DEFAULT TRUE,
    reset_token VARCHAR(100),
    reset_token_expira_em TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE municipios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    codigo_ibge VARCHAR(7) NOT NULL UNIQUE CHECK (LENGTH(codigo_ibge) = 7),
    score_prioridade NUMERIC(5,2) CHECK (score_prioridade IS NULL OR (score_prioridade >= 0 AND score_prioridade <= 100)),
    semaforo VARCHAR(20) NOT NULL CHECK (semaforo IN ('VERDE', 'AMARELO', 'VERMELHO')),
    area_ha NUMERIC(18,2),
    geojson_polygon JSONB,
    nota_risco NUMERIC(4,2),
    kpi_retorno NUMERIC(18,6),
    gasto_publico NUMERIC(18,2),
    resultado_ambiental NUMERIC(18,2),
    pendencias_resumo VARCHAR(2000),
    bioma VARCHAR(20),
    vulnerabilidade_hidrica VARCHAR(20),
    plano_acao_ativo BOOLEAN NOT NULL DEFAULT FALSE,
    ultima_atualizacao TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE indicadores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    municipio_id BIGINT NOT NULL REFERENCES municipios(id) ON DELETE CASCADE,
    ano INTEGER NOT NULL,
    gasto_publico NUMERIC(18,2),
    resultado_ambiental NUMERIC(18,2),
    desmatamento_recente_factor NUMERIC(5,2),
    eficiencia_gasto_factor NUMERIC(5,2),
    irregularidades_car_factor NUMERIC(5,2),
    area_elegivel_factor NUMERIC(5,2),
    empregos_conservacao INTEGER,
    familias_psa INTEGER,
    comunidades_tradicionais INTEGER,
    investimento_social NUMERIC(18,2),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_indicadores_municipio_ano UNIQUE (municipio_id, ano)
);

CREATE TABLE desmatamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    municipio_id BIGINT NOT NULL REFERENCES municipios(id) ON DELETE CASCADE,
    fonte VARCHAR(20) NOT NULL CHECK (fonte IN ('DETER', 'PRODES')),
    data_referencia DATE NOT NULL,
    area_ha NUMERIC(18,2),
    bioma VARCHAR(60) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE alertas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    municipio_id BIGINT NOT NULL REFERENCES municipios(id) ON DELETE CASCADE,
    tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('EMBARGO', 'SOBREPOSICAO', 'CAR_IRREGULAR', 'MANUAL')),
    gravidade VARCHAR(10) NOT NULL CHECK (gravidade IN ('BAIXA', 'MEDIA', 'ALTA')),
    descricao VARCHAR(1500) NOT NULL,
    acao_recomendada VARCHAR(1500) NOT NULL,
    data_alerta DATE NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE emissoes_carbono (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    municipio_id BIGINT NOT NULL REFERENCES municipios(id) ON DELETE CASCADE,
    data_referencia DATE NOT NULL,
    emissao_tco2e NUMERIC(18,4) NOT NULL,
    fonte VARCHAR(255) NOT NULL,
    observacao VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE import_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('PROCESSANDO', 'CONCLUIDO', 'ERRO')),
    registros_inseridos INTEGER NOT NULL DEFAULT 0,
    erros JSONB,
    iniciado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finalizado_em TIMESTAMP WITH TIME ZONE
);

CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    usuario_email VARCHAR(180) NOT NULL,
    acao VARCHAR(60) NOT NULL,
    entidade_afetada VARCHAR(180) NOT NULL,
    evento_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    payload JSONB
);

CREATE INDEX idx_indicadores_municipio ON indicadores(municipio_id);
CREATE INDEX idx_desmatamento_municipio ON desmatamento(municipio_id);
CREATE INDEX idx_alertas_municipio ON alertas(municipio_id);
CREATE INDEX idx_emissoes_municipio ON emissoes_carbono(municipio_id);
