-- V4 - Credito rural de carbono (projecao financeira) e gestao de projetos JREDD+.
-- Consistente com as entidades JPA (Hibernate ddl-auto=validate). Portavel PostgreSQL/H2.

CREATE TABLE creditos_carbono (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    municipio_id BIGINT NOT NULL REFERENCES municipios(id) ON DELETE CASCADE,
    ano_base INTEGER NOT NULL,
    meta_tco2e_ano NUMERIC(18,4) NOT NULL,
    preco_tonelada NUMERIC(18,4) NOT NULL,
    taxa_crescimento_preco NUMERIC(6,4),
    percentual_cumprimento_meta NUMERIC(5,4),
    horizonte_anos INTEGER NOT NULL,
    descricao VARCHAR(1000),
    status VARCHAR(20) NOT NULL CHECK (status IN ('PLANEJADO', 'EM_ANDAMENTO', 'CONCLUIDO', 'CANCELADO')),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE projetos_jredd (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(200) NOT NULL,
    descricao VARCHAR(2000),
    municipio_id BIGINT REFERENCES municipios(id) ON DELETE SET NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('PLANEJADO', 'EM_EXECUCAO', 'SUSPENSO', 'CONCLUIDO', 'CANCELADO')),
    data_inicio DATE,
    data_fim_prevista DATE,
    meta_tco2e NUMERIC(18,4),
    orcamento_previsto NUMERIC(18,2),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE marcos_projeto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    projeto_id BIGINT NOT NULL REFERENCES projetos_jredd(id) ON DELETE CASCADE,
    titulo VARCHAR(200) NOT NULL,
    descricao VARCHAR(1500),
    data_prevista DATE,
    data_conclusao DATE,
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDENTE', 'EM_ANDAMENTO', 'CONCLUIDO', 'ATRASADO')),
    percentual_conclusao INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_creditos_carbono_municipio ON creditos_carbono(municipio_id);
CREATE INDEX idx_projetos_jredd_municipio ON projetos_jredd(municipio_id);
CREATE INDEX idx_marcos_projeto_projeto ON marcos_projeto(projeto_id);
