-- V5 - Plano Safra 2026 (linhas de credito rural com foco em carbono/baixa emissao)
-- e cadastro de instituicoes que compram/certificam credito de carbono.
-- Consistente com as entidades JPA (Hibernate ddl-auto=validate). Portavel PostgreSQL/H2.

-- ---------------------------------------------------------------------------
-- Linhas de credito rural do Plano Safra (RenovAgro/ABC+, Pronaf, etc.).
-- Suporta a sugestao de financiamento para praticas de baixo carbono.
-- ---------------------------------------------------------------------------
CREATE TABLE linhas_credito_safra (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(200) NOT NULL,
    programa VARCHAR(30) NOT NULL CHECK (programa IN
        ('ABC_MAIS', 'RENOVAGRO', 'PRONAF', 'PRONAMP', 'INOVAGRO', 'MODERAGRO', 'OUTRO')),
    ano_safra VARCHAR(9) NOT NULL,
    instituicao_financeira VARCHAR(150),
    taxa_juros_aa NUMERIC(6,4) NOT NULL,
    teto_financiamento NUMERIC(18,2),
    prazo_meses INTEGER,
    carencia_meses INTEGER,
    exige_pratica_carbono BOOLEAN NOT NULL DEFAULT FALSE,
    fator_reducao_tco2e_ha NUMERIC(10,4),
    descricao VARCHAR(2000),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------------
-- Instituicoes que compram, certificam ou intermedeiam credito de carbono.
-- Base para integracao/cadastro e matching com os creditos do estado.
-- ---------------------------------------------------------------------------
CREATE TABLE instituicoes_carbono (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(200) NOT NULL,
    tipo VARCHAR(20) NOT NULL CHECK (tipo IN
        ('CERTIFICADORA', 'COMPRADORA', 'MARKETPLACE', 'VERIFICADORA', 'FUNDO', 'REGISTRO')),
    padrao_certificacao VARCHAR(30) CHECK (padrao_certificacao IN
        ('VERRA_VCS', 'GOLD_STANDARD', 'CERCARBONO', 'PLANVIVO', 'ART_TREES', 'CAR', 'OUTRO')),
    pais VARCHAR(80),
    preco_referencia_tonelada NUMERIC(18,4),
    moeda VARCHAR(3) NOT NULL DEFAULT 'USD',
    site_url VARCHAR(300),
    api_url VARCHAR(300),
    contato_email VARCHAR(150),
    compra_jredd BOOLEAN NOT NULL DEFAULT FALSE,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    observacoes VARCHAR(2000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_linhas_credito_safra_programa ON linhas_credito_safra(programa);
CREATE INDEX idx_instituicoes_carbono_tipo ON instituicoes_carbono(tipo);

-- ---------------------------------------------------------------------------
-- Seed de referencia (Plano Safra 2025/2026 e instituicoes reais do mercado).
-- Valores de taxa/teto sao referencias publicas e podem ser ajustados pelo gestor.
-- ---------------------------------------------------------------------------
INSERT INTO linhas_credito_safra
    (nome, programa, ano_safra, instituicao_financeira, taxa_juros_aa, teto_financiamento,
     prazo_meses, carencia_meses, exige_pratica_carbono, fator_reducao_tco2e_ha, descricao, ativo)
VALUES
    ('RenovAgro / Programa ABC+ - Recuperacao de pastagens', 'ABC_MAIS', '2025/2026',
     'BNDES / Banco do Brasil', 0.0850, 5000000.00, 144, 36, TRUE, 2.5000,
     'Financiamento para recuperacao de pastagens degradadas, integracao lavoura-pecuaria-floresta (ILPF) e sistemas agroflorestais, com reducao comprovada de emissoes.', TRUE),
    ('RenovAgro - Sistemas de plantio direto', 'RENOVAGRO', '2025/2026',
     'Banco do Brasil', 0.0850, 5000000.00, 120, 24, TRUE, 1.2000,
     'Adocao e manutencao de plantio direto na palha, sequestrando carbono no solo.', TRUE),
    ('RenovAgro - Florestas plantadas e recuperacao de APP/Reserva Legal', 'RENOVAGRO', '2025/2026',
     'BNDES', 0.0850, 5000000.00, 180, 96, TRUE, 8.0000,
     'Implantacao e manejo de florestas comerciais e recomposicao de Areas de Preservacao Permanente e Reserva Legal.', TRUE),
    ('Pronaf Bioeconomia', 'PRONAF', '2025/2026',
     'Banco do Brasil / BNB', 0.0500, 250000.00, 120, 36, TRUE, 1.5000,
     'Linha do Pronaf para agricultura familiar voltada a sistemas de base ecologica, agroflorestais e extrativismo sustentavel.', TRUE),
    ('Pronaf Mais Alimentos', 'PRONAF', '2025/2026',
     'Banco do Brasil', 0.0600, 250000.00, 120, 36, FALSE, NULL,
     'Investimento em estrutura produtiva da agricultura familiar.', TRUE),
    ('Pronamp - Investimento', 'PRONAMP', '2025/2026',
     'Banco do Brasil', 0.0800, 1000000.00, 96, 36, FALSE, NULL,
     'Credito de investimento para medio produtor rural.', TRUE),
    ('Inovagro - Tecnologia e agricultura de precisao', 'INOVAGRO', '2025/2026',
     'BNDES', 0.0850, 1500000.00, 120, 36, FALSE, NULL,
     'Incorporacao de inovacao tecnologica nas propriedades rurais.', TRUE);

INSERT INTO instituicoes_carbono
    (nome, tipo, padrao_certificacao, pais, preco_referencia_tonelada, moeda,
     site_url, api_url, contato_email, compra_jredd, ativo, observacoes)
VALUES
    ('Verra (Verified Carbon Standard)', 'CERTIFICADORA', 'VERRA_VCS', 'Estados Unidos', 12.5000, 'USD',
     'https://verra.org', 'https://registry.verra.org/uiapi', NULL, TRUE, TRUE,
     'Maior programa de certificacao voluntaria do mundo (VCS). Metodologias JNR para REDD+ jurisdicional.'),
    ('Gold Standard', 'CERTIFICADORA', 'GOLD_STANDARD', 'Suica', 15.0000, 'USD',
     'https://www.goldstandard.org', NULL, NULL, TRUE, TRUE,
     'Padrao com forte enfase em cobeneficios sociais e ODS.'),
    ('ART / TREES (Architecture for REDD+ Transactions)', 'REGISTRO', 'ART_TREES', 'Estados Unidos', 10.0000, 'USD',
     'https://www.artredd.org', NULL, NULL, TRUE, TRUE,
     'Padrao de referencia para creditos jurisdicionais REDD+ (TREES), base do mercado LEAF.'),
    ('Coalizao LEAF / Emergent', 'COMPRADORA', 'ART_TREES', 'Estados Unidos', 10.0000, 'USD',
     'https://leafcoalition.org', NULL, NULL, TRUE, TRUE,
     'Coalizao publico-privada que compra creditos jurisdicionais REDD+ a preco minimo de USD 10/tCO2e.'),
    ('Cercarbono', 'CERTIFICADORA', 'CERCARBONO', 'Colombia', 8.0000, 'USD',
     'https://www.cercarbono.com', NULL, NULL, FALSE, TRUE,
     'Programa de certificacao voluntaria com atuacao na America Latina.'),
    ('Moss.Earth', 'MARKETPLACE', 'OUTRO', 'Brasil', 30.0000, 'BRL',
     'https://moss.earth', NULL, NULL, FALSE, TRUE,
     'Marketplace brasileiro de creditos de carbono tokenizados (MCO2).'),
    ('BVRio / Bolsa de Carbono', 'MARKETPLACE', 'OUTRO', 'Brasil', 35.0000, 'BRL',
     'https://www.bvrio.org', NULL, NULL, FALSE, TRUE,
     'Plataforma de negociacao de ativos ambientais no Brasil.');
