-- V9 - Base de dados para a Inteligencia preditiva.
--
-- Os calculos de inteligencia (tendencia, projecao, risco, carbono evitado) leem de
-- `desmatamento` e `alertas`, que estavam vazias apos a remocao da ingestao DETER/PRODES.
-- Esta migration:
--   1) Carrega uma serie historica de desmatamento (PRODES anual) por municipio;
--   2) Cadastra alertas (embargo/sobreposicao/CAR) para os municipios de maior prioridade;
--   3) Cria a tabela `projecoes_inteligencia`, onde o RecalculoInteligenciaService
--      armazena o resultado preditivo combinando a serie PRODES com os focos de calor do INPE.
--
-- A serie de desmatamento e um BASELINE derivado de forma deterministica do
-- score de prioridade e do bioma de cada municipio (maior prioridade => mais desmatamento),
-- com leve tendencia de alta nos anos recentes. Os anos sao ancorados em CURRENT_DATE
-- (ultimos 6 anos), de modo que a serie acompanha o calendario e nunca fica "no futuro".
-- Quando uma ingestao oficial (INPE/TerraBrasilis) for executada, ela substitui este baseline.

-- 1) Serie historica de desmatamento (PRODES) - ultimos 6 anos.
INSERT INTO desmatamento (municipio_id, fonte, data_referencia, area_ha, bioma, created_at)
SELECT m.id,
       'PRODES',
       CAST(CONCAT(CAST(CAST(EXTRACT(YEAR FROM CURRENT_DATE) AS INTEGER) - y.off AS VARCHAR), '-08-31') AS DATE),
       ROUND(
         GREATEST(0, 100 - COALESCE(m.score_prioridade, 50))
           * (CASE WHEN m.bioma = 'AMAZONIA' THEN 26 WHEN m.bioma = 'PANTANAL' THEN 14 ELSE 9 END)
           * (1.0 + 0.03 * (6 - y.off))
           + MOD(m.id, 5) * 3,
         2),
       COALESCE(m.bioma, 'CERRADO'),
       CURRENT_TIMESTAMP
FROM municipios m
CROSS JOIN (VALUES (1), (2), (3), (4), (5), (6)) AS y(off);

-- 2) Alertas para municipios de maior prioridade (RN-108: embargo IBAMA, sobreposicao TI/UC, CAR).
INSERT INTO alertas (municipio_id, tipo, gravidade, descricao, acao_recomendada, data_alerta, ativo, created_at, updated_at)
SELECT m.id, 'EMBARGO', 'ALTA',
       'Embargo ambiental ativo (IBAMA) em area do municipio - prioridade alta.',
       'Verificar auto de infracao no SICAFI/IBAMA e suspender a atividade embargada.',
       CURRENT_DATE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM municipios m
WHERE COALESCE(m.score_prioridade, 100) < 50;

INSERT INTO alertas (municipio_id, tipo, gravidade, descricao, acao_recomendada, data_alerta, ativo, created_at, updated_at)
SELECT m.id, 'SOBREPOSICAO', 'MEDIA',
       'Sobreposicao de uso com Terra Indigena (FUNAI) ou Unidade de Conservacao (ICMBio).',
       'Validar limites no Geoportal e acionar orgao gestor da area protegida.',
       CURRENT_DATE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM municipios m
WHERE COALESCE(m.score_prioridade, 100) < 50;

INSERT INTO alertas (municipio_id, tipo, gravidade, descricao, acao_recomendada, data_alerta, ativo, created_at, updated_at)
SELECT m.id, 'CAR_IRREGULAR', 'MEDIA',
       'Imoveis com CAR irregular/cancelado (SICAR) na area do municipio.',
       'Notificar proprietarios para regularizacao do CAR e analise da reserva legal.',
       CURRENT_DATE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM municipios m
WHERE COALESCE(m.score_prioridade, 100) < 50;

INSERT INTO alertas (municipio_id, tipo, gravidade, descricao, acao_recomendada, data_alerta, ativo, created_at, updated_at)
SELECT m.id, 'CAR_IRREGULAR', 'BAIXA',
       'Pendencias pontuais de CAR (SICAR) identificadas no municipio.',
       'Acompanhar regularizacao e priorizar fiscalizacao orientada por risco.',
       CURRENT_DATE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM municipios m
WHERE COALESCE(m.score_prioridade, 100) >= 50
  AND COALESCE(m.score_prioridade, 100) < 70;

-- 3) Tabela de projecoes/resultados preditivos (snapshot mais recente por municipio).
CREATE TABLE projecoes_inteligencia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    municipio_id BIGINT NOT NULL UNIQUE REFERENCES municipios(id) ON DELETE CASCADE,
    ano_base INTEGER,
    tendencia_percent NUMERIC(8,2),
    status_tendencia VARCHAR(20),
    ajuste_score INTEGER,
    taxa_media_anual NUMERIC(8,2),
    media_historica_ha NUMERIC(18,2),
    horizonte_anos INTEGER,
    projecao_json JSONB,
    nota_risco NUMERIC(4,2),
    semaforo_risco VARCHAR(20),
    score_projetado NUMERIC(5,2),
    tco2e_evitado NUMERIC(18,4),
    valor_potencial_reais NUMERIC(18,2),
    focos_calor_ano INTEGER,
    versao_algoritmo VARCHAR(40) NOT NULL,
    calculado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_projecoes_municipio ON projecoes_inteligencia(municipio_id);
